name: CI
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 14
    uses: actions/setup-java@v1
    with:
      java-version: 14

    - name:
      run: mvn -B package --file pom.xml
